### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by ardissaps** [BumbleSoftware/Fastload#10]
https://paste.atlauncher.com/view/ec371e10-3c62-4e92-b45c-7bc8e2f182fa

Look like need compatibility with, coz that mod is quite big deal for most :
https://www.curseforge.com/minecraft/mc-mods/fabrication

**Comment by StockiesLad** [comment]
Will fix, no ETA's.

**Comment by StockiesLad** [comment]
done
