### ISSUE TITLE
update to fabric 1.20.1

### ISSUE THREAD

**Issue by skibidibada** [BumbleSoftware/Fastload#104]
idk why its updated for forge but not for fabric

**Comment by Felix14-v2** [comment]
> idk why its updated for forge but not for fabric

FastLoad 3.4.0 works without any issues in Minecraft 1.20.1, in fact, it doesn't even have a hard version dependency:
![image](https://github.com/BumbleSoftware/Fastload/assets/75726196/aa1ea486-7e31-47a0-b9c4-0676a0f2f3ac)
So, version for 1.20 must work
https://modrinth.com/mod/fastload/version/3.4.0

@StockiesLad , can you mark this version as compatible with 1.20/1.20.1, so people can find it using version filter? Currently only forge version is shown:
![image](https://github.com/BumbleSoftware/Fastload/assets/75726196/4b88d42c-d6b3-4e33-9ed9-66e23147fd13)

**Comment by StockiesLad** [comment]
> > idk why its updated for forge but not for fabric
> 
> FastLoad 3.4.0 works without any issues in Minecraft 1.20.1, in fact, it doesn't even have a hard version dependency: ![image](https://user-images.githubusercontent.com/75726196/247239336-aa1ea486-7e31-47a0-b9c4-0676a0f2f3ac.png) So, version for 1.20 must work https://modrinth.com/mod/fastload/version/3.4.0
> 
> @StockiesLad , can you mark this version as compatible with 1.20/1.20.1, so people can find it using version filter? Currently only forge version is shown: ![image](https://user-images.githubusercontent.com/75726196/247240489-4b88d42c-d6b3-4e33-9ed9-66e23147fd13.png)

It's for future proofing incase on the off chance it *does* work. Does it actually work though?

Also,
I don't work on this mod anymore....

**Comment by Felix14-v2** [comment]
> Does it actually work though?

At least for me. I didn't encounter any problems using it.

**Comment by sternschnaube** [comment]
Mod works fine on Fabric 1.20.1.
Version listing on Modrinth should be marked as compatible for it.

**Comment by StockiesLad** [comment]
I'll list it as compatible then...
