### ISSUE TITLE
JEI is not showing in the first load

### ISSUE THREAD

**Issue by crest1993** [BumbleSoftware/Fastload#11]
While opening the world JEI is not showing, I have to Save and Quit to Title and then reopen the world to make it work. Is this a bug or just JEI bug on their end? It is faster though.

**Comment by StockiesLad** [comment]
Hmmm, I don't have this issue on my end. I'll look into it though!

**Comment by StockiesLad** [comment]
Oh shit! JEI, not REI. I wouldn't have a clue. I'll have to ask the forge lead about this.

**Comment by crest1993** [comment]
Yeah I'm surprised too, JEI support fabric now haha. I think JEI is better with performance, I dunno, might be wrong too.

**Comment by AbdElAziz333** [comment]
I tested the issue but it works fine with me,
Which Fastload version you are using?
Which JEI version you are using?
Which Forge version you are using?

**Comment by StockiesLad** [comment]
what other mods are there and provide logs as well.

**Comment by StockiesLad** [comment]
Issue is stale... unable to reproduce
