### ISSUE TITLE
MC v1.20.1 Incompatible

### ISSUE THREAD

**Issue by DemonSeedxp** [BumbleSoftware/Fastload#113]
### What went wrong?

Fastload fails to load with error requires version 1.19.1

### Reproduction steps

1. {Mods required}
2. {Conditions}
3. {Execution}
4. {Failure}
...
Minecraft 1.20.1 loading with fastload = error

### Visual demonstration

![Screenshot 2024-03-30 055315](https://github.com/BumbleSoftware/Fastload/assets/11554194/bce7c957-f7b8-49b5-9eb2-dc8b1074542a)

### Crash Report & Log

[latest log](https://github.com/BumbleSoftware/Fastload/files/14811414/latest_stdout.log)

### Fastload Config

Default Config

### Environment

Fastload 3.4.0, Fabric 0.15.7, Minecraft 1.20.1

**Comment by VOrlando520** [comment]
This mod was abandoned and the original dev isn't coming back from the looks of it outside of snooping on his discord on an alt so.

**Comment by DemonSeedxp** [comment]
pshh well that figures. sad part is he did take the time to add support to this version, but just screwed up the tags so it gets rejected. 

oh well, thanks for the in site

**Comment by DemonSeedxp** [comment]
closed as wont fix
