### ISSUE TITLE
Crash with this mod

### ISSUE THREAD

**Issue by Funtimes909** [BumbleSoftware/Fastload#12]
[latest.log](https://github.com/BumbleSoftware/Fastload/files/8937838/latest.log)
Something to do with fabric API?
Stops crashing when the mod is removed

**Comment by StockiesLad** [comment]
its incompatible with adventure platform fabric.

**Comment by StockiesLad** [comment]
I don't touch the same methods as that mod so Idk why it would crash.

**Comment by StockiesLad** [comment]
it says its a snapshot. 
"- adventure-platform-fabric 5.4.0-SNAPSHOT via tabtps-fabric"
