### ISSUE TITLE
Server loop stopping when player loads with fastload

### ISSUE THREAD

**Issue by MrJorman** [BumbleSoftware/Fastload#17]
When a player connects, my MSPT goes up from 4 to 15-20 and runs the server.

Minecraft: 1.19 Fabric

I had such a problem on Forge, but I fixed it with some kind of mod, like FastLoad or krypton or ksyxis, but then I put a lot of optimization and I don't know how to fix it. When a player connects to the server, it freezes.

**Comment by StockiesLad** [comment]
ksyxis isnt supposed to be with fastload... and MSPT going up when a player joins is normal.

**Comment by MrJorman** [comment]
It's not normal, the server freezes when loading the player. On Forge, some mod fixed it, like APTweaks.

**Comment by MrJorman** [comment]
I don't use Fast Load and Ksuxis mods together.

**Comment by StockiesLad** [comment]
Did u try with just fastload?

**Comment by MrJorman** [comment]
yes, i use.

**Comment by StockiesLad** [comment]
Is fastload both present on server and client?

**Comment by MrJorman** [comment]
yes

**Comment by StockiesLad** [comment]
Can u just try with it just on client, and tell me if the issue persists. Test it by itself please!

**Comment by MrJorman** [comment]
I checked, the problem persists.

**Comment by MrJorman** [comment]
I tested it without your mod too.

**Comment by StockiesLad** [comment]
Okay, can you join the discord for better means of communication?

**Comment by MrJorman** [comment]
ok

**Comment by StockiesLad** [comment]
I actually do not know what is happening here, nor do I know how to reproduce/resolve this.

**Comment by StockiesLad** [comment]
Ok, I figured it out. It is simply the product of the way this mod is made. This mod takes certain shortcuts that really shouldn't be done. There is no practical way to fix this.
