### ISSUE TITLE
FastLoad stopping world creation and slowing world loading (at least for me on a Mac :p)

### ISSUE THREAD

**Issue by DTRW919** [BumbleSoftware/Fastload#19]
logs: https://mclo.gs/EiT5nmi

When creating a world, it always gets stuck at 100%, and just spams `[Server thread/INFO]: Not the long loadi-` in the logs. Removing the mod completely negates this weirdly. Also consistently slows down world loading by a couple seconds.

I hope that the mod soon will make my game even better! Cheers, and good luck.

**Comment by StockiesLad** [comment]
Remove ksyxis
