### ISSUE TITLE
Crash on start-up with Create and Click Machine [1.18.2, Forge]

### ISSUE THREAD

**Issue by Nevrai** [BumbleSoftware/Fastload#20]
Fastload seems to be incompatible with [Create](https://www.curseforge.com/minecraft/mc-mods/create) and [Click Machine](https://www.curseforge.com/minecraft/mc-mods/click-machine), as both mods cause the game not to boot. The game boots normally when removing Fastload.

**Crash report:** https://pastebin.com/raw/PV53H1z9

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Fastload:** Fastload Reforged 1.1.5 (latest)
* **Create:** 0.5.0c (latest)
* **Click Machine:** 6.0.5 (latest)
* **Java:** OpenJDK 17.0.1

**Comment by Foxydapirate12** [comment]
Ok, so i've tested this with the mods installed and came across no issues on my end, perhaps try updating forge or java.
Link for forge here: https://files.minecraftforge.net/net/minecraftforge/forge/
Link for Java here: https://www.oracle.com/java/technologies/downloads/#java17
![Screenshot 2022-08-05 045019](https://user-images.githubusercontent.com/101042481/182930527-7ffc7a8e-d133-48ce-bdef-800c30f0e21e.jpg)

**Comment by Foxydapirate12** [comment]
Also you've got two max memory arguments in the java arguments (Should be one)

**Comment by Foxydapirate12** [comment]
Ok @DeleteMetaInf, I've found the cause, the cause is TooFast, it's server-side only and not meant to be installed on the client

![Screenshot 2022-08-05 221608](https://user-images.githubusercontent.com/101042481/183075717-508bba4f-dcad-46ff-977a-123255a97b09.jpg)
![Crash cause](https://user-images.githubusercontent.com/101042481/183075872-bbc62e51-3ee7-4cc2-87ed-33a6ff1ea650.jpg)

**Comment by Nevrai** [comment]
Thanks for finding the issue! I don’t know why there are two max RAM arguments. I’m using [GDLauncher](https://gdevs.io/), so it must be an issue with the launcher. I don’t think it affects anything, though.

I’m playing a single-player world, not on a server, so server-side mods have to also be installed on the client. Is it possible you could fix this issue, or is it an issue on [Too Fast’s](https://www.curseforge.com/minecraft/mc-mods/too-fast) end?

**Comment by StockiesLad** [comment]
Okay, forge has a redundant mixin. Messaged the forge lead to remove this. Will close when build is ready

**Comment by Nevrai** [comment]
Thanks for [the update](https://www.curseforge.com/minecraft/mc-mods/fastload/files/3921115)! I’ll try it out. I presume it fixes this issue, so I’ll close it. Much appreciated!

**Comment by StockiesLad** [comment]
This is all thanks to the forge lead. I'll let him know of your gratitude
