### ISSUE TITLE
[forge-1.18] Slow loading after encrypting phase

### ISSUE THREAD

**Issue by jinkhya** [BumbleSoftware/Fastload#24]
Hello!
I'm trying out this mod in ATM7 modpack and I noticed that it's rather fast to see the beginning of the loaded game : I can see my hotbar, my hand but the rest of the world is not loaded and it takes about 15-20 seconds to see the rest and be able to do anything. I checked the time it takes to load with and without fastload and it's the same except I can see my empty hotbar/hand a lot sooner. I hope it makes sense it's kinda hard to describe :)

here's a video, maybe it'll be easier to understand : 
https://streamable.com/peqioh

I'm playing on a server and the mod is present in both.

modpack: ATM7 0.4.32
fastload version : 1.2.0
forge version : 40.1.80

Thanks in advance !

**Comment by StockiesLad** [comment]
don't use fastload. The networking seems too overloaded. Fastload will just overstress it.

**Comment by StockiesLad** [comment]
or atleast just turn off the "close loading screen unsafely"

**Comment by jinkhya** [comment]
oh so the forge version is not working as well as the fabric one?

**Comment by StockiesLad** [comment]
I doubt that. It's probably just a CPU/network limitation.

**Comment by jinkhya** [comment]
I have a Ryzen 5900X and about 120Mbps 
The server is a dedicated box with a 5950X with 1 Gbit/s

I doubt that's the issue

**Comment by StockiesLad** [comment]
it's not that simple

**Comment by StockiesLad** [comment]
the limitations of mc itself

**Comment by StockiesLad** [comment]
the packet handlers, huge amount of ram with a lot of mods + high cpu usage = no room to increase speed with fastload.
