### ISSUE TITLE
Softlocking the game when using Fastload alongside FTB Quests

### ISSUE THREAD

**Issue by choombdev** [BumbleSoftware/Fastload#26]
Installing the latest forge version, FTB Quests (and it's dependencies) and Fastload causes a bug to happen where once you click on the Quest hotkey (for example, grave) and open the quests menu then click again, a 'Joining World' screen is overlaid on top which stays there forever, softlocking the game. the Server or Singleplayer world (if pause is disabled) keeps moving too behind the load screen.

I believe this is caused by FTB Quests quickly shows the 'Loading Terrain' screen on it's own and since Fastload removes that screen, this happens. 

**Forge Version:** 
Latest (40.1.84)
**Mods loaded:**
Fastload-Reforged-1.2.1+1.18.2.jar
ftb-quests-forge-1802.3.8-build.101.jar
ftb-library-forge-1802.3.6-build.140.jar
ftb-teams-forge-1802.2.6-build.69.jar
item-filters-forge-1802.2.8-build.47.jar
architectury-4.10.86-forge.jar

**Comment by StockiesLad** [comment]
I don't seem to get this on fabric. I would suggest reporting this to FTB quests. This is a bug on their end that just happens to get exacerbated with fastload.

**Comment by KirboSoftware** [comment]
@FluffyBumblebees this is on forge, not fabric.....

**Comment by StockiesLad** [comment]
I know, it's the same code for FTB quests

**Comment by StockiesLad** [comment]
Bc it uses architectury
