### ISSUE TITLE
Document the configurations for Fastload

### ISSUE THREAD

**Issue by Kichura** [BumbleSoftware/Fastload#27]
The only details that Fastload alone has are the technical explanations such as comparisons and all that, however when reviewing the configs themselves; they lack any documentation on what they actually do and what is recommended for a normal user.

**Comment by StockiesLad** [comment]
Good point, I'll do that.

**Comment by StockiesLad** [comment]
In Experimental build. No ETA's yet

**Comment by StockiesLad** [comment]
Since the experimental branch will be released soon, I will close this.
