### ISSUE TITLE
[Experimental Branch] Fastload causes crashes on latest commit.

### ISSUE THREAD

**Issue by Kichura** [BumbleSoftware/Fastload#28]
When joining specific servers like Hypixel, Fastload has a possibility of crashing with the "this.oldPitch" script in MinecraftClientMixin.java being null instead of a proper float value instead.

**Comment by StockiesLad** [comment]
Okay! Thanks for the issue report. Must be a small oversight on my experimental branch!

**Comment by StockiesLad** [comment]
Do you have logs? I need them to see exactly what situation asked for it when it was null.

**Comment by StockiesLad** [comment]
Fixed
