### ISSUE TITLE
[CRASH] 1.19.2 Reforged 1.3.2 Crashes on server startup

### ISSUE THREAD

**Issue by MihailDenisov** [BumbleSoftware/Fastload#31]
Crashes on server startup, Forge 43.1.52

[crash-2022-11-10_00.59.12-fml.txt](https://github.com/BumbleSoftware/Fastload/files/9975540/crash-2022-11-10_00.59.12-fml.txt)
[debug.log](https://github.com/BumbleSoftware/Fastload/files/9975541/debug.log)
[latest.log](https://github.com/BumbleSoftware/Fastload/files/9975542/latest.log)

**Comment by katubug** [comment]
Occurs in 1.18.2 as well, forge 40.1.84

**Comment by StockiesLad** [comment]
This is fixed in the latest upstream, it will be released when the forge lead has time
