### ISSUE TITLE
[Fabric] Console spam on latest version whilst in modded environment

### ISSUE THREAD

**Issue by pokesmells** [BumbleSoftware/Fastload#36]
https://user-images.githubusercontent.com/33227568/203872456-256fcbad-261b-4118-8fcf-74d12f7df4b6.mp4

**Comment by StockiesLad** [comment]
los?

**Comment by StockiesLad** [comment]
logs*?

**Comment by Poke097** [comment]
[Uploading latest.txt…]()

**Comment by pokesmells** [comment]
[latest.txt](https://github.com/BumbleSoftware/Fastload/files/10087658/latest.txt)
I didn't get crash logs so here's the latest log

**Comment by StockiesLad** [comment]
can you turn on debug mode?

**Comment by StockiesLad** [comment]
then boot it up, and post the log

**Comment by StockiesLad** [comment]
Could u also send ur current config?

**Comment by pokesmells** [comment]
I apologize for the late reply, was in uni, anyways how do  go about enabling debug mode in the server's config?

**Comment by pokesmells** [comment]
[config.zip](https://github.com/BumbleSoftware/Fastload/files/10088702/config.zip)
Here is the server config file

**Comment by StockiesLad** [comment]
> I apologize for the late reply, was in uni, anyways how do go about enabling debug mode in the server's config?

Debug mode for fastload in the same config that u just gave me.

**Comment by StockiesLad** [comment]
Debug mode should tell me precisely where somethings failing

**Comment by pokesmells** [comment]
[latest.txt](https://github.com/BumbleSoftware/Fastload/files/10095784/latest.txt)
The spam went away after turning debug mode on or it was a coincidence

**Comment by StockiesLad** [comment]
hmm that's actually really weird.

**Comment by StockiesLad** [comment]
Since I have finished another project I was working on, I can fully focus on this issue now and resolve it

**Comment by StockiesLad** [comment]
Do you have a public modpack or something that I can install to replicate this issue?

**Comment by pokesmells** [comment]
Why yes I do haha

**Comment by pokesmells** [comment]
https://www.curseforge.com/minecraft/modpacks/a-little-bit-of-everything-fabric/files

**Comment by pokesmells** [comment]
I have a server pack as well

**Comment by ghost** [comment]
it is probably caused by the mod not actualy re-reading the config after resetting it. it also applies to cases where the config file is not present afaik

**Comment by StockiesLad** [comment]
I'm gonna delegate responsibility to @JoostMSoftware as I will be taking a break from modding. See discord for more info. This might also make this issue take longer to resolve. Sorry! I hope you guys understand!

**Comment by KirboSoftware** [comment]
I will take a look at it when I'm feeling better, apologies for the delay. But this will most likely been taken care of next week at minimum sadly.

**Comment by StockiesLad** [comment]
can u try on the latest version?

**Comment by StockiesLad** [comment]
Closed as there hasn't been a response for 1 month now.
