### ISSUE TITLE
Minecraft freezes on startup

### ISSUE THREAD

**Issue by voidrinix** [BumbleSoftware/Fastload#38]
Hello! Today I updated fastload from 2.4.2 to 2.4.4 and my mc freezed on startup, I also tried 2.4.3 and nothing changed. Only 2.4.2 works well.

MC version: 1.19.2
Modloader: Quilt 0.17.7
NVIDIA Driver version: 525.60.11
OS&PC info: 
![изображение](https://user-images.githubusercontent.com/73175330/205490502-2276291b-483a-40d8-a0f2-d9cfb0d19575.png)

**Comment by StockiesLad** [comment]
Could you try to replicate the issue on a fabric instance?

**Comment by StockiesLad** [comment]
If it does indeed happen again, could you provide the logs?

**Comment by voidrinix** [comment]
wtf, I tried again and now it works. I think there is no more issue

**Comment by StockiesLad** [comment]
Hmm interesting. Feel free to reopen this issue if it reappears!
