### ISSUE TITLE
[BUG] Empty world

### ISSUE THREAD

**Issue by Kiryonn** [BumbleSoftware/Fastload#39]
I'm on **W11 AMD integrated graphic card** using **Fastload 2.4.4 (Fabric)** (Yup. The worst OS with the worst kind of "GPU"). I can log into Minecraft just fine, and load my world just "fine", but when I'm actually in the world, it's just empty (but not really). I keep falling but the game detects there should be a block below me so it tp's me back to my login position.

**Comment by StockiesLad** [comment]
I would recommend for you to turn off “force close loading screen”. If that doesnt work, turn on the pre rendering screen.

**Comment by StockiesLad** [comment]
Let me know if that works

**Comment by Kiryonn** [comment]
i'll try that when i'm home thanks.

**Comment by StockiesLad** [comment]
1 month of inactivity, closing.
