### ISSUE TITLE
Port to Forge for Minecraft 1.18.2

### ISSUE THREAD

**Issue by Talbe1** [BumbleSoftware/Fastload#42]
Since the last port to Forge it seems that there have been major changes (and **optimizations**) to the mod for its Fabric and Quilt version. Please make a newer port for Forge if there will be more demand for it.

**Comment by StockiesLad** [comment]
I already notified the forge dev. Join the discord if you want to speak with him regarding the forge verison.

**Comment by Talbe1** [comment]
Do you think that I should talk to him? I'm not sure if it will help, or if it has a point at all.

Also, (and this isn't related to the mod) I got to say, I **DID NOT** expect to receive a reply from someone on Github this quickly 🤣
Don't get me wrong, replying quickly is a good thing, I just didn't expect it to be that fast.

**Comment by StockiesLad** [comment]
webhooks are indeed special. Anyways, the reason why I referred to the forge lead is for questions. Since I do not work on it, questions regarding dev, ETA & such are only accurately answered by him.

**Comment by Talbe1** [comment]
Okay, I'll try to talk to him. Thanks!

**Comment by StockiesLad** [comment]
Sounds good!

**Comment by StockiesLad** [comment]
It has been updated.
