### ISSUE TITLE
FancyMenu crash with latest FastLoad reforged

### ISSUE THREAD

**Issue by Proxwian** [BumbleSoftware/Fastload#45]
When I trying to connect server via custom button in FancyMenu, game crashes. Not happens with 1.2.1 version

[crash-2022-12-25_00.21.23-client.txt](https://github.com/BumbleSoftware/Fastload/files/10298966/crash-2022-12-25_00.21.23-client.txt)

**Comment by StockiesLad** [comment]
Weird. I just looked at the crash report and I don't even understand how it is crashing. We'll have to wait until fastload reforged updates to the latest version to see if it still occurs.

**Comment by StockiesLad** [comment]
can u try with the latest fastload for forge?

**Comment by Proxwian** [comment]
Can confirm that with latest versions of FastLoad and FancyMenu issue was solved, thanks
