### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [BumbleSoftware/Fastload#50]
To make it for Minecraft 1.12.2. If it's not possible, could You give me a link to Minecraft 1.12.2 alternative mod ?

**Comment by FluffyBumblebees** [comment]
1.12.2 will never happen. And, there is no alternative mod that I know of.

**Comment by Kasia1403** [comment]
@FluffyBumblebees Could You explain me why it will never happen ?

**Comment by FluffyBumblebees** [comment]
bc the codebase is far too different and don't have the time to backport it.
