### ISSUE TITLE
Suggestion: config option to skip fades

### ISSUE THREAD

**Issue by Godeps2891** [BumbleSoftware/Fastload#51]
While not really making loads faster I think it'd be nice to have an option to skip the fade ins for the loading screen / mojang logo

similar to what the No Fade mod did

https://github.com/UltimateBoomer/mc-no-fade
![image](https://raw.githubusercontent.com/UltimateBoomer/mc-no-fade/assets/images/demo.gif)

**Comment by StockiesLad** [comment]
This is not within the goals of fastload. Fastload optimises world loading, not anything else.
