### ISSUE TITLE
Android: Entering a singleplayer world works, joining multiplayer crashes the game.

### ISSUE THREAD

**Issue by GaucovyAero** [BumbleSoftware/Fastload#52]
Native C input has been recently added into PojavLauncher ([PR here](https://github.com/PojavLauncherTeam/PojavLauncher/pull/4006)), which dramatically increases performance in versions using LWJGL3 (1.13+). As a result of native input being added, Fastload crashes when joining multiplayer, but singleplayer works just fine.

**What's in the log:**
1. I launched Minecraft 1.19.3, Fabric 0.14.14
2. I entered my singleplayer world, no errors. Then I quit the world and went back to the main menu.
3. I joined `mc.qplay.cz` (this can be any server)
4. Game crashed.

**System specs:**
**Device:** Poco F3 8/256GB
**SoC:** Qualcomm Snapdragon 870
**GPU:** Qualcomm Adreno 650
**Renderer:** Holy GL4ES 1.1.4 (OpenGL 2.1 with OpenGL 3.2 shaderconv)
**OS:** MIUI 13.0.9.0 (Android 12)

[Log is attached](https://github.com/BumbleSoftware/Fastload/files/10892105/latestlog.txt). 
[Here is a conversation](https://user-images.githubusercontent.com/85581164/222968849-cecae3cd-20c4-4e71-96dc-fcb1aa89b890.png) with artDev (PojavLauncher dev) that might explain better what's happening.

**Comment by StockiesLad** [comment]
I'm not going to rewrite parts of my mod so a 3rd party launcher works for it. If my mod works perfectly natively, then it's an issue with pojav's implementation.
