### ISSUE TITLE
[Crash] Unknown Crash

### ISSUE THREAD

**Issue by NaiNonTH** [BumbleSoftware/Fastload#57]
Once I launched the game with Fastload V3.0.1 installed on the Quilt of Minecraft 1.19.4, it showed me this error:
[crash-2023-04-04_20.37.29-client.txt](https://github.com/BumbleSoftware/Fastload/files/11149174/crash-2023-04-04_20.37.29-client.txt)

Here are some other details:
* **Minecraft Version:** 1.19.4
* **Quilt Loader Version:** 0.18.5
* **Quilt Fabric API Version:** 5.0.0-beta.2_fapi-0.76.0

**Comment by StockiesLad** [comment]
Please read the changelog
