### ISSUE TITLE
Inventory item icons not rendered until updated by a player event

### ISSUE THREAD

**Issue by HaXrDEV** [BumbleSoftware/Fastload#6]
Items will disappear when changing worlds on a multiplayer server. Sometimes you can simply left-click in the inventory and the items will re-appear and other times it requires a complete relog of the server before the items become visible again. 

This happens when playing on a vanilla 1.19 paper server with the Multiverse plugin installed. 
The issue is not present when using a vanilla client or removing the mod.

**Comment by StockiesLad** [comment]
Sounds like the server is lagging behind… try to use it with other optimisation mods like lithium, c2me and starlight to see if it does anything.

**Comment by StockiesLad** [comment]
Fixed in the latest build!
