### ISSUE TITLE
Q&A regarding Fastload Reforged stale development

### ISSUE THREAD

**Issue by Atlantispy** [BumbleSoftware/Fastload#62]
Hi,

Sorry to be that guy, will the recent significant updates be ported to the forge version? 

I assume the forge lead dev is quite busy given how many mods he works on.

Thanks

**Comment by StockiesLad** [comment]
Honestly I got no idea what's happening regarding Fastload Reforged but I'll try to explain the context for you and you can come to your conclusion:

As you already said he is busy, while fastload uses yarn mappings, has been abstracted, uses an internal api, uses fabric-exclusive modloading tricks to get fabric api to work through multiple versions, and is solely reliant on mixin. This makes it very hard to realistically port to forge. The latest forge version is so far behind as of this point that it'd practically require an entire rewrite. This mod has gotten more features, a far better codebase, at the consequence of complexity. The code is very complex for what it does. To the outside eye, fastload is hard to understand, let alone modify. I do not doubt for a second that AbdElAziz333 is incapable of porting it, but it would be tedious and difficult for him to do so.

There is good news. Soon, fastload will soon stabilise on a certain feature set for an indefinite amount of time as I polish everything to my liking. Which will allow room for AbdElAziz333 to port it without worry of having to spend time maintaing it.

**Comment by KirboSoftware** [comment]
I mean, a possible thing that we could do is work with Architectury (not using the API, just the gradle plugin and arch loom) to make it work both ways (Fabric and Forge) in 1 development space, tho I don't know how well it will work with mixins. There is only one way to really find out well it will work
