### ISSUE TITLE
FastLoad auto-closes/hides Resource pack prompt

### ISSUE THREAD

**Issue by Andre601** [BumbleSoftware/Fastload#64]
When joining a server with a required resource pack and using FastLoad, is the prompt to download the pack or leaving the server shown for a split second before being gone completely.

The client isn't kicked after this from the server, meaning that the prompt is still "open", but is not displayed.

Disabling or removing FastLoad fixes the issue.

List of other mods I use (In case it's a incompatability issue):

- 3D Skin Layers 1.5.3-mc1.19.4
- Concurrent Chunk Management Engine 0.2.0+alpha.10.42
- Continuity 3.0.0-beta.2+1.19.3
- EntityCulling-Fabric 1.6.2-mc1.19.4
- Exordium 1.0.3-mc1.19.4
- FerriteCore 5.2.0
- FirstpersonModel 2.2.3
- ImmediatelyFast 1.1.11
- Indium 1.0.15+mc1.19.4
- Inspecio 1.8.0+1.19.4
- Krypton 0.2.2
- LambDynamicLights 2.3.0+1.19.4
- LazyDFU 0.1.3
- Lithium 0.11.1
- Memory Leak Fix 1.0.0
- Mod menu 6.1.0-rc.4
- More Culling 1.19.4-0.17.0
- NotEnoughAnimations 1.6.3
- Presence Footsteps 1.8.0
- Smooth Boot 1.19.4-1.7.0
- Sodium 0.4.10+build.24
- Reese's Sodium Options 1.5.0+mc1.19.4-build.72
- Starlight 1.1.1+fabric.ae22326
- Very Many Players 0.2.0+beta.7.69

I want to also mention that I'm using Quilt with QuiltLoader 0.18.8

**Comment by StockiesLad** [comment]
Fixed
