### ISSUE TITLE
New incompatibility with Remove Reloading Screen

### ISSUE THREAD

**Issue by DreenDex** [BumbleSoftware/Fastload#67]
Env: fabric 1.19.4
Fastload+ version: 1.18.2-1.19.4-3.2.0
Remove Reloading Screen version: Rrls-1.5.0-fabric

Reproduction:
1) Open minecraft in minimized windowed mode
2) Go to singleplayer
3) Open any world (i use the arrow button on the latest world icon)
4) Maximize the window while world is still loading (double click on the window titlebar)
5) Main game menu opens as well as you join the world, but you can't play it because you can't close the main menu.
6) Try going to the singleplayer again, and in the world list there is no world you just joined because minecraft client incorrectly handles world file lock in the case of the same game process accessing it.

**Comment by DreenDex** [comment]
Upon further investigation, it turned out to be a compatibility issue with the [Remove Reloading Screen](https://modrinth.com/mod/rrls) mod. Before this FastLoad update everything was working fine.

**Comment by DreenDex** [comment]
The problematic part in RemoveReloadingScreen is this [code line](https://github.com/dimadencep/RemoveReloadingScreen/blob/13752c4bcaaae4c8f8c9cc5a89d1290c673d85b4/common/src/main/java/com/github/dimadencep/mods/rrls/mixins/MinecraftClientMixin.java#L62). It closes the world loading screen fine, but some "magic" from latest Fastload+ update made it so if method `MinecraftClient::setScreen` invoked with screen set to `null`, it sets the current screen to Main menu instead of null. Provided behaviour of this method is described in fabricmc yarn documentation.

![image](https://user-images.githubusercontent.com/6661231/230646825-99284065-9b66-4464-ba3f-fa9bb0e842e6.png)

So Fastload+'s part either (1) effectively delays the setting of Minecraft::world field or (2) opens a screen that extends DownloadingTerrainScreen too early. Therefore main menu opens instead of loading screen closing.

**Comment by StockiesLad** [comment]
> The problematic part in RemoveReloadingScreen is this [code line](https://github.com/dimadencep/RemoveReloadingScreen/blob/13752c4bcaaae4c8f8c9cc5a89d1290c673d85b4/common/src/main/java/com/github/dimadencep/mods/rrls/mixins/MinecraftClientMixin.java#L62). It closes the world loading screen fine, but some "magic" from latest Fastload+ update made it so if method `MinecraftClient::setScreen` invoked with screen set to `null`, it sets the current screen to Main menu instead of null. Provided behaviour of this method is described in fabricmc yarn documentation.
> 
> ![image](https://user-images.githubusercontent.com/6661231/230646825-99284065-9b66-4464-ba3f-fa9bb0e842e6.png)
> 
> So Fastload+'s part either (1) effectively delays the setting of Minecraft::world field or (2) opens a screen that extends DownloadingTerrainScreen too early. Therefore main menu opens instead of loading screen closing.

It overrides LevelLoadingScreen. It doesn't delay the loading of ClientWorld. I'll try to conditionally load fastload and try my best to stop it from interferring with other loading screens.

**Comment by StockiesLad** [comment]
Actually upon more thought, when the pre rendering is disabled. It will use DownloadingTerrainScreen early. Please test whether this still happens when it is enabled.

**Comment by StockiesLad** [comment]
Issue seems to be fixed here.
