### ISSUE TITLE
Consider putting a big "Are you sure you want to enable this?" warning

### ISSUE THREAD

**Issue by Sogardd** [BumbleSoftware/Fastload#69]
The Instant Load option has a tooltip saying that the user will regret turning the feature on, however, if you don't read the small tooltip, you can easily corrupt a world accidentally.

**Comment by StockiesLad** [comment]
It does not corrupt anything. It just is really laggy and makes you end up waiting longer.

**Comment by StockiesLad** [comment]
thus, the regret

**Comment by Sogardd** [comment]
> It does not corrupt anything. It just is really laggy and makes you end up waiting longer.

I must have opened a world that was already corrupted then? It said "failed to load datapacks", I opened it in safe mode and then it said "This world contains invalid or corrupted data".

weird coincidence I guess
