### ISSUE TITLE
[1.19 Fabric] Nether Portal Issue 

### ISSUE THREAD

**Issue by dog-biscuit64** [BumbleSoftware/Fastload#7]
Just using the mod clientside and not on the server

Going through any nether portal in the overworld places on the nether roof at spawn (0, 128, 0). Going through any portal in the nether places you at the overworld spawn. Maybe this is something that happens if this mod isn't installed on the server, but thought I'd mention it since I have to stop using it for now.

**Comment by FluffyBumblebees** [comment]
I'll try to recreate this issue. Are there any other mods? Could you also provide logs?

**Comment by FluffyBumblebees** [comment]
Is this on forge or fabric?

**Comment by StockiesLad** [comment]
Ok, I reproduced the issue, it seems like the player is spawning too early. I do end up teleporting back at the portal though. it seems like this is a bug related to the server...

**Comment by StockiesLad** [comment]
This is a weird issue...

**Comment by StockiesLad** [comment]
It's a teleporting issue that I'll need to fix. This bug subsequently causes #6

**Comment by dog-biscuit64** [comment]
Yea, I went in through the portal and still had all my gear on me, but it wasn't appearing/loading in the GUI. Relogging makes it reappear but doesn't fix the whole teleporting to spawn issue. I don't wanna have anyone stuck on the nether roof. Do you think having the mod on the server would fix this? The other mods I have are the primary ones Sodium, Lithium, etc. After removing this mod, that issue went away. It first happened to me last night on the previous version and again today on the latest version.

**Comment by StockiesLad** [comment]
This is an issue within the playerentity management, I need to fix this with an update.

**Comment by StockiesLad** [comment]
Fixed in the latest build!
