### ISSUE TITLE
Group Fastload & child mods into one tab in modmenu [Requires new mod menu feature]

### ISSUE THREAD

**Issue by forditt** [BumbleSoftware/Fastload#70]
I think it should be grouped:
![зображення](https://user-images.githubusercontent.com/105544922/230721872-b68306ec-6964-4f5d-9107-5de187ef3e67.png)![зображення](https://user-images.githubusercontent.com/105544922/230721908-23675bf4-489f-4eb3-bea9-397ea198350a.png)

**Comment by StockiesLad** [comment]
That's a thing? I'll do that

**Comment by StockiesLad** [comment]
Ahh, I was just looking at the mod menu api, it seems that this is a new feature? This will be lower priority and take longer then expected.

**Comment by Felix14-v2** [comment]
> it seems that this is a new feature?

Nope, this is a pretty old feature. Just specify the parent in fabric.mod.json:

```
  "custom": {
    "modmenu": {
      "parent": {
        "id": "fastload"
      }
    }
  }
```

**Comment by StockiesLad** [comment]
> > it seems that this is a new feature?
> 
> Nope, this is a pretty old feature. Just specify the parent in fabric.mod.json:
> 
> ```
>   "custom": {
>     "modmenu": {
>       "parent": {
>         "id": "fastload"
>       }
>     }
>   }
> ```

oh! I had no idea. Thanks, I'll do this rn.

**Comment by forditt** [comment]
> Ahh, I was just looking at the mod menu api, it seems that this is a new feature? This will be lower priority and take longer then expected.

no, it was a long time ago

**Comment by StockiesLad** [comment]
> > Ahh, I was just looking at the mod menu api, it seems that this is a new feature? This will be lower priority and take longer then expected.
> 
> no, it was a long time ago

ye I realised I was looking at the wrong thing after flex replied

**Comment by StockiesLad** [comment]
anyways this is completed now
