### ISSUE TITLE
With V3.2.x+ Mod incompatible with Bedrock-Loading-Animation from BedrockIfy

### ISSUE THREAD

**Issue by Cape-City** [BumbleSoftware/Fastload#71]
I'm using the Fabric Loader with MC 1.19.3 and i love loading screens and if you get interessting information, it's absolutly fantastic. That's why i love the Bedrock-Loading-Animation from BedrockIfy. Loading things quickly is awesome too, so i had the mod Fastload installed. The Version 3.1.1 of Fastload does nothing with BedrockIfy, but the latest V3.3.1 is skipping the alternate loadingscreen and shows it's own "starting session" and then further chunk-load information, instead of just adding them to the existing loadingscreen. Also there is no way in the config, which can disable the behavior.

**Comment by StockiesLad** [comment]
> I'm using the Fabric Loader with MC 1.19.3 and i love loading screens and if you get interessting information, it's absolutly fantastic. That's why i love the Bedrock-Loading-Animation from BedrockIfy. Loading things quickly is awesome too, so i had the mod Fastload installed. The Version 3.1.1 of Fastload does nothing with BedrockIfy, but the latest V3.3.1 is skipping the alternate loadingscreen and shows it's own "starting session" and then further chunk-load information, instead of just adding them to the existing loadingscreen. Also there is no way in the config, which can disable the behavior.

It's not as simple as just "adding them to the existing loading screens". That's not how it works. Fastload changes how loading worlds works. I can probably rectify this situation with mixin, but I cannot guarantee it'll be clean. For the best results, please report this issue to bedrockify to see if they have hooks into the loading screen such that I can add my own information in there.

**Comment by Cape-City** [comment]
Thanks for your response, i reported this issue to BedrockIfy - really hope that they can assist to get both your mods compatible. You're both doin' such great work and making MC even more better, everyone in his special way!

https://github.com/juancarloscp52/BedrockIfy/issues/265

Happy easter ;)

**Comment by StockiesLad** [comment]
> Thanks for your response, i reported this issue to BedrockIfy - really hope that they can assist to get both your mods compatible. You're both doin' such great work and making MC even more better, everyone in his special way!
> 
> [juancarloscp52/BedrockIfy#265](https://github.com/juancarloscp52/BedrockIfy/issues/265)
> 
> Happy easter ;)

Thank you! I do my best to ensure compat. I'm sure it won't be too hard.

**Comment by Cape-City** [comment]
Hi,

the issue is solved and will be adressed with the update from the BedrockIfy mod.
