### ISSUE TITLE
Server Render Chunk Radius documentation is incorrect

### ISSUE THREAD

**Issue by Kichura** [BumbleSoftware/Fastload#73]
The specific config makes use of a value instead of a boolean and as result does not reflect the documentation's description well,
and attempting to set the `server_render_chunk_radius` to boolean instead makes the mod itself assume the entire config is now broken instead.

**Comment by StockiesLad** [comment]
O oops. I'll fix that.

**Comment by StockiesLad** [comment]
Fixed
