### ISSUE TITLE
Whats going on with the versioning?

### ISSUE THREAD

**Issue by itsdinkd** [BumbleSoftware/Fastload#74]
You set the filename to have the MC version, but then on the upload it is for all MC versions?

This is my modpack for 1.19.2, but it shows 1.18.2, and 1.19.4 versions of fastload that can be installed.

![image](https://user-images.githubusercontent.com/35115304/231243665-75a00987-d0ff-45e6-bdcf-35e02089da94.png)

**Comment by StockiesLad** [comment]
1.18.2 all the way to 1.19.4

that includes 1.19.2
