### ISSUE TITLE
Suggestion: Add option to disable screen of "Preparing All Chunks"

### ISSUE THREAD

**Issue by NoltoxGit** [BumbleSoftware/Fastload#75]
Hello !

Since I don't know which update, this [loading screen](https://user-images.githubusercontent.com/75265787/231443420-85b8dc6a-4759-45de-9c32-dc4c5cde1748.png) appears, and I personally find it quite annoying, I would prefer before when it didn't appear.

Would it be possible with a configuration via ModMenu, to disable this screen please?

Thanks a lot,
~ Noltox ~

**Comment by StockiesLad** [comment]
The config file documents everything. You can set it to 0 to disable
