### ISSUE TITLE
Client crashes on startup

### ISSUE THREAD

**Issue by maxguuse** [BumbleSoftware/Fastload#76]
Crash-report:
[crash-2023-04-14_01.45.30-client.txt](https://github.com/BumbleSoftware/Fastload/files/11227250/crash-2023-04-14_01.45.30-client.txt)

Minecraft works fine without fastload

**Comment by StockiesLad** [comment]
I dont even touch this class. Send full log

**Comment by StockiesLad** [comment]
Without a response, im going to conclude that this is owo lib and not fastload's problem.
