### ISSUE TITLE
crash when loading world, building terrain screen

### ISSUE THREAD

**Issue by harithmf** [BumbleSoftware/Fastload#79]
https://gist.github.com/harithmf/ed994beb552f6f221da45676569c50cf

https://gist.github.com/harithmf/cb91a18f86e460acb6fbc34b10f07d95

**Comment by StockiesLad** [comment]
can u send the full lag, the crash report doesnt give enough information

**Comment by StockiesLad** [comment]
upon second read, fastload isnt in the stacktrack besides my screen name, some architectury mixin is breaking stuff.

**Comment by StockiesLad** [comment]
ye report this to architectury and link this page

**Comment by StockiesLad** [comment]
This bug hasn't gotten a response at all so i'm going to close it as nobody else has this issue

**Comment by xbxct** [comment]
The world is really endlessly loaded and because of unknown incompatibilities.
