### ISSUE TITLE
The world with captcha does not start

### ISSUE THREAD

**Issue by Tema159** [BumbleSoftware/Fastload#81]
Starting from Fastload version 3.2.0 - the world with captcha does not want to start. For example, you can take a server with the IP "mc.kachanovcraft.com" (not advertising) and try to log in from the fastload version:
1. 3.1.1;
2. 3.2.0 and newer.
On this server, in new versions of Fastload, the loading screen freezes, but the captcha check times out.
![2023-04-20_20 17 21](https://user-images.githubusercontent.com/114809383/233440822-2df8f2b5-25d5-43c2-aa3c-c154d68e4080.png)

**Comment by StockiesLad** [comment]
did u turn the chunk try limit to max? because if you did, that explains why. putting it to max will make it never end. I just looked at the text and there is no warning i'll try adding it. But in the meantime, set the chunk try limit to like 500.

**Comment by Tema159** [comment]
I did not set any restrictions, the config is configured by default. Try to access this server from version 3.1.1, and from version 3.2.0 (and newer)

**Comment by StockiesLad** [comment]
can you try turning the "chunk try limit" to 0.

**Comment by StockiesLad** [comment]
also try sending log with debug mode on pls.

**Comment by Tema159** [comment]
"chunk try limit" automatically jumps from 0 to 1.
Log: [latest.log](https://github.com/BumbleSoftware/Fastload/files/11293610/latest.log)

**Comment by StockiesLad** [comment]
ah yes to 0 my bad. it cant be less thean 0.

**Comment by StockiesLad** [comment]
hmm weird. It should be cancelling after hitting the chunk try limit.

**Comment by StockiesLad** [comment]
does it work when the server pre render radius is set to 1?

**Comment by StockiesLad** [comment]
If not, can u try to reproduce this issue with fastload by itself. If it still fails, can u try to replicate on fabric with just fastload?

**Comment by Tema159** [comment]
1 doesn't work. I already checked fabric - unsuccessfully

**Comment by StockiesLad** [comment]
weird... it must be some event issue. I will look into this

**Comment by StockiesLad** [comment]
Fastload+1.18.2-1.19.4-3.3.7.jar

try this jar

**Comment by StockiesLad** [comment]
hold on what is github doing?

**Comment by StockiesLad** [comment]
[Fastload+1.18.2-1.19.4-3.3.7.zip](https://github.com/BumbleSoftware/Fastload/files/11303288/Fastload%2B1.18.2-1.19.4-3.3.7.zip)
There we go. just extract this and try the jar

**Comment by Tema159** [comment]
It works, but please return the vanilla minecraft loading square

**Comment by StockiesLad** [comment]
1. Level Loading Screen is for singleplayer.
2. That was already asked and explained in: #82 & #68
