### ISSUE TITLE
With FastLoad death menu don't work properly

### ISSUE THREAD

**Issue by ImGRUI** [BumbleSoftware/Fastload#84]
No logs.
Without FastLoad works perfectly.
Quilt 0.18.10, latest QFAPI
Minecraft 1.19.4
FastLoad 3.3.7
Showcase:

https://user-images.githubusercontent.com/91282421/233854448-ad50515d-3abe-4916-be97-15a8667a55bd.mp4

**Comment by StockiesLad** [comment]
Strange, ill look into this

**Comment by StockiesLad** [comment]
What are your settings? is it default?

**Comment by StockiesLad** [comment]
I can't reproduce

**Comment by StockiesLad** [comment]
ahh its because of instant load, ill fix this

**Comment by StockiesLad** [comment]
fixed
