### ISSUE TITLE
Sounds don't stop between switching worlds

### ISSUE THREAD

**Issue by Kaizodude** [BumbleSoftware/Fastload#85]
Switching between worlds on servers doesn't forcefully stop playing sounds, resulting in them carrying over to the next
Video: https://youtu.be/uZ5VYezwZls
Modlist shown in image, this didn't occur prior to FastLoad being installed
![image](https://user-images.githubusercontent.com/2174905/234089617-4e0aa118-2d31-458a-950c-34e819bbb14d.png)

**Comment by Kichura** [comment]
Confirmed as switching from nether dimension to overworld continues playing the background noises until F3 + T is pushed.

**Comment by StockiesLad** [comment]
what are the settings for the fastload config?

**Comment by Kaizodude** [comment]
> what are the settings for the fastload config?

Default, nothing was changed

**Comment by StockiesLad** [comment]
weird

**Comment by StockiesLad** [comment]
alright i need some things guys.

What sounds in specific?
Does it happen with instant load config?
Does it happen with just fastload?
How would one replicate this effectively without having to wait for the sounds to happen?

**Comment by Kichura** [comment]
> alright i need some things guys.
> 
> What sounds in specific? Does it happen with instant load config? Does it happen with just fastload? How would one replicate this effectively without having to wait for the sounds to happen?

Mostly the ambience sounds that play whenever you are in specific nether biomes,
Yes it happens there too for some reason,
Can seem to confirm,
Just switch to nether and head to a biome that has ambience sounds then instantly go back to overworld using portal or execute command.

**Comment by StockiesLad** [comment]
> > alright i need some things guys.
> > What sounds in specific? Does it happen with instant load config? Does it happen with just fastload? How would one replicate this effectively without having to wait for the sounds to happen?
> 
> Mostly the ambience sounds that play whenever you are in specific nether biomes, Yes it happens there too for some reason, Can seem to confirm, Just switch to nether and head to a biome that has ambience sounds then instantly go back to overworld using portal or execute command.

thanks bro this is going to go a long way to help me test

**Comment by StockiesLad** [comment]
now just running some tests

**Comment by StockiesLad** [comment]
fixed
