### ISSUE TITLE
[1.18.2 Fabric] newest Update requires at least MC 1.19.3

### ISSUE THREAD

**Issue by MSandro** [BumbleSoftware/Fastload#87]
![image](https://user-images.githubusercontent.com/10937159/234180792-d317ddfd-f637-4fbd-9e71-c521a89e3f32.png)
Fastload+1.18.2-1.20-3.3.8

**Comment by Talbe1** [comment]
I have no problem launching my 1.18.2 Fabric client. Could it be that you modified the fabric.mod.json file that is inside the .jar file? Maybe try redownloading the mod.

**Comment by MSandro** [comment]
in my case I've updated the Mods: Spark and Fastload at the same time.
Spark caused the issue. I've downgraded Spark and now the newest Fastload Version is working well.

**Comment by icynstant** [comment]
When i have some problems that aren't related to Fastload I can see this issue with Fastload. So when I fix my problem, issue with Fastload will disappear too.

![Screenshot_1](https://github.com/BumbleSoftware/Fastload/assets/127024748/71d5a524-b707-4298-be84-f369a92dcd3d)

I think I saw issue like mine but rn I can't find it.
