### ISSUE TITLE
Getting stuck at session creation when joining a server

### ISSUE THREAD

**Issue by Andre601** [BumbleSoftware/Fastload#91]
### What went wrong?

When joining a server while using Fastload 3.4.0 does the client get stuck at the session step.

Disabling FastLoad also fixes this join issue.

I want to point out that this happened to me on a Server network and after being redirected from one server to another (The first server was used to load a resource pack before being redirected to the main servers).

### Reproduction steps

I'm using the following sets of Mods on a Quilt 1.19.4 setup:

- 3d Skin Layers 1.5.3
- Concurrent Chunk Management Engine 0.2.0+alpha.10.51
- Continuity 3.0.0-beta.2
- EntityCulling-Fabric 1.6.2
- FerriteCore 5.2.0
- FirstpersonModel 2.2.3
- ImmediatelyFast 1.1.12
- Indium 1.0.17
- Inspecio 1.8.0
- Krypton 0.2.2
- LambDynamicLights 2.3.0
- LazyDFU 0.1.3
- Lithium 0.11.1
- Memory Leak Fix 1.0.0
- MixinExtras 0.2.0
- Mod-Menu 6.2.2
- More Culling 0.17.0
- NotEnoughAnimations 1.6.3
- Presence Footsteps 1.8.0
- Reese's Sodium Options 1.5.0-build.72
- Smooth Boot 1.7.0
- Sodium 0.4.11
- Starlight 1.1.1+fabric.ae22326
- Very Many Players 0.2.0+beta.7.71

1. Start the client
2. Join a Server
3. Encounter the session loading indefinitely.

### Visual demonstration

Video showing the issue: https://youtu.be/i_-STyHxVCw

### Crash Report & Log

Client Log: https://mclo.gs/AXJskAa

No crashes happen during start or other actions (i.e. server join)

### Environment

FastLoad 3.4.0
Quilt Loader 0.18.8
Minecraft 1.19.4

**Comment by StockiesLad** [comment]
I can't seem to reproduce the issue. Can you please see if it still happens with just fastload. If no, try to find the mod that causes the issue when paired with fastload.

**Comment by Tetsuyamin** [comment]
I have tested under a few mod combinations and it seems that the mod combination of Sodium 0.4.11 and Fastload 3.4.0 causes the same issue when going through a Waterfall portal.

**Comment by StockiesLad** [comment]
alright

**Comment by StockiesLad** [comment]
[Fastload+1.18.2-1.20-3.4.0.zip](https://github.com/BumbleSoftware/Fastload/files/11419230/Fastload%2B1.18.2-1.20-3.4.0.zip)
can u try this jar?

**Comment by Poopooracoocoo** [comment]
Switching servers gets further but nothing is visible and the attack indicator is present. Here's a screenshot of me after joining the Hypixel main lobby, right clicking on the compass and selecting Bed Wars. 

Minecraft 1.19.4, Fabric Loader 0.14.19. Only mods are your build of Fastload, Sodium 0.4.11, and Fabric API 0.80.0.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/51363864/236830149-7b448f01-8f3a-420a-b86f-59cd1593747e.png">

Logs: https://mclo.gs/H1KxZ8W

**Comment by StockiesLad** [comment]
hmm maybe im breaking the frustum.

**Comment by StockiesLad** [comment]
Sodium 0.4.10 seems to be working. 0.4.11 was removed for having too many issues. Can you guys test to see if the same applies to you.

**Comment by Andre601** [comment]
Using 3.4.0 with Sodium 0.4.10 seems to work fine.

**Comment by StockiesLad** [comment]
ye then it was sodium breaking it bc sodium 0.410 was breaking a lot of other mods. reopen this  issue if this problem occurs again.
