### ISSUE TITLE
Game Crashes when loading onto a certain server

### ISSUE THREAD

**Issue by ghost** [BumbleSoftware/Fastload#94]
Step to reproduce:
1. Join bakery.dedimc.io
2. click the building area NPC

Note: This only happens on this server.

**Comment by ghost** [comment]
[message.txt](https://github.com/BumbleSoftware/Fastload/files/11423458/message.txt)
The Log/Crash Report

**Comment by Poopooracoocoo** [comment]
Duplicate of #91

**Comment by StockiesLad** [comment]
Im closing this because I don't appreciate you just using a blank template to submit your bug report when I made when with specifics I need.

**Comment by StockiesLad** [comment]
It might've been my fault actually. The issue template disappeared. Sorry for being a dick. If this issue still occurs you are more then welcome to reopen this.
